# Generated by Django 2.2.1 on 2019-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_todolist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='level',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
