# Generated by Django 2.2.1 on 2019-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0003_todolist_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='level',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
